### ISSUE TITLE
BOM & CAD

### ISSUE THREAD

**Issue by claytono** [rollybot/Delta_Square_V1#1]
This looks like a really interesting project.  I don't read Korean, but I looked at the rollybot.com website and don't see the BOM there.  Are you planning to release the CAD for this project?

**Comment by lyangj** [comment]
Yes.  I am preparing the bom and files.  Im still uploading other files to github.  I have plan to finish uploading v1 in a month.  And v0 in 3 months. 

나의 iPhone에서 보냄
